-- Exercise 1

-- Create Database and Table
CREATE DATABASE nf;

CREATE TABLE NF (
    ID_NF INTEGER NOT NULL,
    ID_ITEM INTEGER NOT NULL,
    COD_PROD INTEGER NOT NULL,
    VALOR_UNIT DECIMAL(10 , 2 ),
    QUANTIDADE INTEGER NOT NULL,
    DESCONTO INTEGER
);

-- Populating database

INSERT INTO NF (ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES (1, 1, 1, 25.00, 10, 5),
		(1, 2, 2, 13.50, 3, null),
		(1, 3, 3, 15.00, 2, null),
		(1, 4, 4, 10.00, 1, null),
		(1, 5, 5, 30.00, 1, null),
		(2, 1, 3, 15.00, 4, null),
		(2, 2, 4, 10.00, 5, null),
		(2, 3, 5, 30.00, 7, null),
		(3, 1, 1, 25.00, 5, null),
		(3, 2, 4, 10.00, 4, null),
		(3, 3, 5, 30.00, 5, null),
		(3, 4, 2, 13.50, 7, null),
		(4, 1, 5, 30.00, 10, 15),
		(4, 2, 4, 10.00, 12, 5),
		(4, 3, 1, 25.00, 13,5),
		(4, 4, 2, 13.50, 15,5),
		(5, 1, 3, 15.00, 3, null),
		(5, 2, 5, 30.00, 6, null),
		(6, 1, 1, 25.00, 22,15),
		(6, 2, 3, 15.00, 25,20),
		(7, 1, 1, 25.00, 10, 3),
		(7, 2, 2, 13.50, 10, 4),
		(7, 3, 3, 15.00, 10, 4),
		(7, 4, 5, 30.00,10 ,1);

SELECT * FROM NF;

-- item a
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT
FROM NF
WHERE DESCONTO IS NULL;

-- item b
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT,
		ROUND(VALOR_UNIT - (VALOR_UNIT * (DESCONTO / 100)), 2) AS VALOR_VENDIDO
FROM NF
WHERE DESCONTO IS NOT NULL;
  
-- item c
UPDATE NF 
SET DESCONTO = 0
WHERE DESCONTO IS NULL;

-- item d
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT,
    DESCONTO, ROUND(VALOR_UNIT - (VALOR_UNIT * (DESCONTO / 100))) AS VALOR_VENDIDO,
		QUANTIDADE * VALOR_UNIT AS VALOR_TOTAL 
FROM NF;
  
-- item e
SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL
FROM NF
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

-- item f
SELECT ROUND(SUM(VALOR_UNIT - (VALOR_UNIT * (DESCONTO / 100))), 2) AS VALOR_VENDIDO, ID_NF
FROM NF
GROUP BY ID_NF
ORDER BY VALOR_VENDIDO DESC;

-- item g
SELECT COD_PROD, SUM(QUANTIDADE) AS QUANTIDADES
FROM NF
GROUP BY COD_PROD
ORDER BY QUANTIDADES DESC
LIMIT 1;

-- item h
SELECT ID_NF, COD_PROD, QUANTIDADE
FROM NF
GROUP BY ID_NF, COD_PROD
HAVING QUANTIDADE > 10;

-- item i
SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL
FROM  NF
GROUP BY ID_NF
HAVING VALOR_TOTAL > 500
ORDER BY VALOR_TOTAL DESC;

-- item j
SELECT COD_PROD, ROUND(AVG(DESCONTO), 2) AS MEDIA
FROM NF
GROUP BY COD_PROD;

-- item k
SELECT COD_PROD,
    ROUND(AVG(DESCONTO), 2) AS MEDIA,
    MAX(DESCONTO) AS MAIOR,
    MIN(DESCONTO) AS MENOR
FROM NF
GROUP BY COD_PROD;

-- item l
SELECT ID_NF, COUNT(QUANTIDADE) AS QUANTIDADES
FROM NF
GROUP BY ID_NF
HAVING QUANTIDADES > 3;
